### ISSUE TITLE
Height as percentage of superview in visual layout

### ISSUE THREAD

**Issue by nderkach** [freshOS/Stevia#121]
Is there a way to specify heights as a percentage of superview in visual layout?

For instance, I have the following layout:

```
        layout(
            30,
            phoneImageView,
            36,
            titleLabel,
            28,
            subtitleLabel
        )
```

and I want to swap the spacing between items from a fixed one to a percentage-based one relative to the superview height, e.g. soemthing like:

```
        layout(
            10%,
            phoneImageView,
            12%,
            titleLabel,
            8%,
            subtitleLabel
        )
```

I could do `phoneImageView.top(10%)` separately, but it's not clear how to achieve that between the other views.

Also, I wondering is there is a way to specify the height of an individual view as a percentage of the superview height as well, something like:

```
        layout(
            ...
           phoneImageView ~ 30%,
            ...
```

**Comment by s4cha** [comment]
@nderkach Thanks a ton for reporting this, this does looks like something we'd want to support indeed. Before we start implementing it, could you provide the native way of creating those constraints for each case please ?

**Comment by nderkach** [comment]
To specify the height of a view relative to a height of the superview I can do something like:

```NSLayoutConstraint.activate([subview.heightAnchor.constraint(equalTo: view.heightAnchor, multiplier: 0.5)])```

To add relative height for padding in the seconds example, I see at least a couple options:

* ```NSLayoutConstraint.activate([subview.topAnchor.constraint(equalTo: view.heightAnchor, constant: view.bounds.height * 0.5)])```

* Add a dummy view and set it's `heightAnchor` with a multiplier.

The first option might not always work, as the view geometry might be not yet calculated at the time of the call. There might also be a better way to achieve this I"m not aware of.

**Comment by s4cha** [comment]
@nderkach Thanks a ton for taking the time to find native ways to achieve this behaviour, this is greatly appreciated.

For simplicity's sake, we are going to address all these cases separately.
A)` phoneImageView ~ 30%,` is a very good idea and actually trivial to implement:
```swift
@discardableResult
public func ~ (left: UIView, right: SteviaPercentage) -> UIView {
    return left.height(right)
}
```
This is going to be added for next version.

B) The following `top` and `bottom` margins in layout blocks:
```swift
layout(
  10%,
  phoneImageView,
  //...
   subtitleLabel
  30%
)
```
are easy to implement as well.

C) Vertical inter percentage space are the most tricky.
```swift
layout(
  phoneImageView,
  25%,
  subtitleLabel
)
```
As you pointed out, when using auto layout we never want to explicitly reference frames or bounds so option 1 is out. I believe the only way to achieved this properly is to introduce UILayoutGuides (aka same as dummy views). While feasible, this does complexity the layout pass since we add UI (invisible) elements to the view. Finally I think that B) without C) would be misleading so both use cases should be implemented together or not at all. I am going to try an implementation and will report back :)

**Comment by s4cha** [comment]
@nderkach An implementation has been done which should cover all of your use cases.
You can try it by pointing Swift package manager to the latest commit `78e4dde215ca96df5fcc8b97d7026119c892d2b2` Let mw know if that works for you and we'll push a new version :)

**Comment by s4cha** [comment]
@nderkach You should be able to support all your layouts in the latest [5.0.0](https://github.com/freshOS/Stevia/releases/tag/5.0.0) version (and much more!) 
Enjoy :)

**Comment by s4cha** [comment]
Closing this as the api requested are now live :)
