### ISSUE TITLE
how to make a view take remaining space

### ISSUE THREAD

**Issue by biskit** [freshOS/Stevia#44]
if i have

button
|
View
|
button

how do I make View take all remaining vertical space?

**Comment by chetem** [comment]
Just set constraints on the buttons and let the view fill in the rest. Something like this..

```
|-buttonA-| ~ 40,
20,
|-view-|,
20,
|-buttonB-| ~ 40
```

This will create a button (buttonA) pinned to the top of it's superview with height 40, and left/right margins of the default 8. Another button (buttonB) will be pinned to the bottom with the same height and left/right margins. The view in the middle will fill all remaining space with a top and bottom margin of 20. If you don't want the margins, just omit them or set it to 0 if you like

**Comment by s4cha** [comment]
@chetem  Thanks for chiming in ;)
@biskit Did that solve your issue?

Cheers,

**Comment by biskit** [comment]
i believe that did not work as that's the most intuitive thing to try first. i had to manually compute heights to make it happen.

**Comment by s4cha** [comment]
@biskit 
To make it stick to the bottom you need to add a bottom margin like so

```swift
layout(
  0,
  |-buttonA-| ~ 40,
  20,
  |-view-|,
  "",
  |-buttonB-| ~ 40,
  0 // <--
)
```

The "" essentially means "Free space" so it will not constraint the adjacent views.
Setting a fixed space will then strech the view as wanted.

```swift
layout(
  0,
  |-buttonA-| ~ 40,
  20,
  |-view-|,
  20,
  |-buttonB-| ~ 40,
  0
)
```
We are going to document this better since it might not be super intuitive,
Thanks a lot for you time ;)
