### ISSUE TITLE
how to decide which view to shrink

### ISSUE THREAD

**Issue by hpsoar** [freshOS/Stevia#55]
I have a row, with layout like:

|-password.width(100)-label-label2-| ~ 80,

label & label2 are UILabel with long text.

The result is
label shrunk to a width that can't display the full text.
but label2 can display full text.

I wan't the contrary: label2 got shrunk, and label show the full text

what should I do?

here attached the result
<img width="316" alt="screen shot 2016-07-29 at 4 50 00 pm" src="https://cloud.githubusercontent.com/assets/1549522/17242938/7fc02312-55ac-11e6-9fed-74a849c0d8b2.png">

**Comment by s4cha** [comment]
Hi @hpsoar 
This has todo with content compression resistance and content hugging resistance.
You can find nice explanation here :
http://krakendev.io/blog/autolayout-magic-like-harry-potter-but-real

"**Content Hugging Priority** - The higher this priority is, the more a view resists growing larger than its intrinsic content size."

"**Content Compression Resistance Priority** - The higher this priority is, the more a view resists shrinking smaller than its intrinsic content size."

```swift
label.setContentCompressionResistancePriority(1000, forAxis: .Horizontal)
```
This should do the trick ;)

**Comment by hpsoar** [comment]
This works, thank you.

Can you add the compression & hugging priority setter available like the width in the following layout expression?

|-password.width(100)-label-label2-| ~ 80,

So developers can write code like

|-password.width(100)-label.compresssionPriority(1000, .Horizontal)-label2-| ~ 80,

|-password.width(100)-label.huggingPriority(1000, .Horizontal)-label2-| ~ 80,

I'm not quite sure whether this is a good propose yet  ;)

**Comment by s4cha** [comment]
@hpsoar 
This is something that was not top priority since the gain in terms of conciseness are somewhat discussable : 
`compresssionPriority(1000, .Horizontal)` vs.  
`setContentCompressionResistancePriority(1000, forAxis: .Horizontal)`

and the fact that theses helpers are seldom needed. Only in some layouts, like yours.

I'm not against the idea though it could be pretty straightforward to implement.
If you're willing to give it try, I invite you to issue a Pull request that we can review together.

Please excuse the late reply, have a great day  :)

**Comment by s4cha** [comment]
@hpsoar Can we close this ?

**Comment by n13** [comment]
Easiest to make your own UIView extension with a doNotCompress() function.

As for how rare this is, the very first view I ever created with Stevia layout needed this. So ... ;)
