### ISSUE TITLE
Using Stevia We don't need starboard at all ?

### ISSUE THREAD

**Issue by lakshmibomma** [freshOS/Stevia#65]
Hi,

Please provide the clarification on these questions.
1. Using Stevia We don't need starboard or xib  at all ?.(I thought it is only for layout the views,still we need storyboard and xib files with view controllers)
2. Does the app run through command line.

**Comment by s4cha** [comment]
Hi @lakshmibomma,

1. The purpose of Stevia, indeed, is to solve all the issues related with Storyboards or Xibs. 
The view controllers stay in code, the only difference is that the view is accessed directly for the VC instead of having to link IBOutlets or IBActions.
Our main App Yummypets, has no storyboards nor Xibs at all, all the views ( ~ hundreds !) are in code.
This is actually a very common and old practise, Stevia only makes those view files easier to deal with :)
 
2. Can you elaborate on this ?

Cheers,

**Comment by lakshmibomma** [comment]
Thank you very much. You guys did a great job on auto layout constraints.I just want to make sure that still it needs storyboard and the auto layout is done with stevia(IBOutlets and IBActions).I am  also under same assumption thats stevia is for auto layout the view.
My app I am still using storyboards and layout the view I am using stevia. 
Is there any way to run the app through command line..any idea

**Comment by s4cha** [comment]
@lakshmibomma the goal is to get away from Storyboard, and Stevia makes the code more readable, so there should be no Storyboards in the end :)
