### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ugur10** [freshOS/Stevia#76]
Hi Sacha,

Great lib, congrats 👏

Is it possible to add a benchmark or comparison somehow with respect to the Storyboard version performance of the same app?

I may use Stevia, but to convince myself, I have to see its performance gain a bit clearer I think.

Thanks!

Ugur

**Comment by s4cha** [comment]
@ugur10 

Better late than never :)

Stevia is **pure** auto layout so theoretically, it has the same performances as Autoloayout in code.

I know that Apple has some optimisations on nibs under the hood when loading storyboards.
Still, since Storyboards are using auto layout the performances at runtime should be the same.

I haven't found any comparisons online so If you find some I'd be very curious.
Be assured that you are the first one to ask such a question and I have never been concerned personally. (We have a social app with a Facebook-like feed that scrolls like butter)

Hopes this helps,

Cheers,

**Comment by ugur10** [comment]
Awesome answer! =)

I have probably lots of storyboard based implementations right now, and I still prefer it like this. It may be "less typing" ideals on my mind, or the visual appeal, I don't know =)

One thing I can request from you, is a simple application, like one with some segues, a tableview with images etc. to add it as an Example application. It would be awesome =)

Cheers! =)

**Comment by s4cha** [comment]
@ugur10 

Here is a project taken from http://freshos.org that showcases how Stevia (and some of our other tools) work together in a typical iOS App.
(I tweaked it a bit so that it works out of the box for you)

WeTransfer Download link : https://we.tl/EbMVm8rKAI

Hope it helps you see how to implement it in your own App,

Again please excuse the late reply :)

**Comment by ugur10** [comment]
No problems man, you have got such a great work here. Thanks a ton! =)
