### ISSUE TITLE
Iphone X layout issue

### ISSUE THREAD

**Issue by Rozariozaro** [freshOS/Stevia#80]
There is no option for safe area for iphone 10 layout. Please update.

**Comment by Narsail** [comment]
Agree. Would like to use the safe area as well. :)

**Comment by s4cha** [comment]
@Narsail @Rozariozaro I am looking at it at the moment :)

Would you have examples of your own code where you use the native api for `safeAreaLayoutGuide` and the counterpart of how you would like to write it with Stevia ?

That would be super useful so that we design an api we're all happy with.

Here is my take on this:

Example:
```swift
startButton.bottomAnchor.constraint(equalTo: safeAreaLayoutGuide.bottomAnchor, constant: -20).isActive = true
```

```swift
startButton.BottomAnchor == safeAreaLayoutGuide.BottomAnchor - 20
```

Technically, this involves bridging anchors with wrapping Stevia structs and providing == operator overloads, following the same idea already used for `.Top` `.CenterY` etc.

Essentially it would be used through the Equation based api.

Would love your thoughts on that!

Cheers,

**Comment by s4cha** [comment]
@Narsail @Rozariozaro any updates?

**Comment by Narsail** [comment]
Sry for not answering. At the moment it isn't in my focus and I hadn't time to think about it lately. Sry! Doesn't look like this will change soon.

**Comment by s4cha** [comment]
No problem, closing this for now as latest releases supports `safeAreaLayoutGuide` in equation api :)

**Comment by petritz** [comment]
I like using layout(), but as soon as there is a UINavigationBar and an iPhone X I have issues. Is there an easy way to solve this problem? Thanks.
