### ISSUE TITLE
Problem with equal width

### ISSUE THREAD

**Issue by pbrazdil** [freshOS/Stevia#82]
I have this layout UIViewController -> UIView view -> UIScrollView scrollView -> UIView contentView -> ...

I've set subviews and everything necessary.

But I have an issue with one NSLayoutContraint I am unable to rewrite into Stevia. I need to set equal width for the view and contentView.

Code of constraint: 
```
view.addConstraint(NSLayoutConstraint(item: contentView, attribute: .width, relatedBy: .equal, toItem: view, attribute: .width, multiplier: 1, constant: 0))
```

I've tried following lines but none of them worked.
```
equalWidths(contentView, view)
view.Width == contentView.Width
contentView.Width == view.Width
```

 Either producing error that view is not in the hierarchy (which it is) or it does literally nothing.

**Comment by s4cha** [comment]
@pbrazdil 
I recently faced the same "issue".

As a good practice, Stevia adds constraints to the superview.

The problem arises when we constrain views that are not on the same Z-index in the view hierarchy.
This is quite rare, but it's needed sometimes and your case is a perfect example.


The underlying reason is that  `equalWidths(contentView, view)` actually translates into 👍 
```swift
view.SUPERVIEW.addConstraint(
  NSLayoutConstraint(
            item: contentView,
            attribute: .width,
            relatedBy: .equal,
            toItem: view,
            attribute: .width,
            multiplier: 1,
            constant: 0)
)
```
I have to see what we can do to handle this case in a clean way.
In the meantime, falling back to the native way as you did is a safe bet.

Hope this helps,

**Comment by s4cha** [comment]
```swift
@discardableResult
public func == (left: SteviaAttribute, right: SteviaAttribute) -> NSLayoutConstraint {
    let constant = right.constant ?? 0
    let multiplier = right.multiplier ?? 1
    if let spv = left.view.superview {
        return spv.addConstraint(item: left.view,
                                 attribute: left.attribute,
                                 toItem: right.view,
                                 attribute: right.attribute,
                                 multiplier : multiplier,
                                 constant:constant)
    }
    return NSLayoutConstraint()
}
```
In this case,  superview is nil which explains why nothing happens :)

Ideally I think we want to check if B is a child A and if so add the constraint on the A rather than the superview. the question is how to do that without adding overhead for all the other cases, suggestions are welcome.
Cheers,

**Comment by s4cha** [comment]
Hey @pbrazdil,

I've been working on a fix on a branch :)
https://github.com/freshOS/Stevia/tree/zindex

Be aware that the following only applies to the `==` operator for now.

Here is the fix for reference, given two views `A` and `B`

```swift
if left.view.superview == right.view.superview { // A and B are at the same level
    // The way it was done before for every case
    if let spv = left.view.superview {
        return spv.addConstraint(item: left.view,
                                 attribute: left.attribute,
                                 toItem: right.view,
                                 attribute: right.attribute,
                                 multiplier: multiplier,
                                 constant: constant)
    }
} else if left.view.superview == right.view { // A is in B (first level)
    return right.view.addConstraint(item: left.view,
                                    attribute: left.attribute,
                                    toItem: right.view,
                                    attribute: right.attribute,
                                    multiplier: multiplier,
                                    constant: constant)
} else if right.view.superview == left.view { // B is in A (first level)
    return left.view.addConstraint(item: right.view,
                                   attribute: right.attribute,
                                   toItem: left.view,
                                   attribute: left.attribute,
                                   multiplier: multiplier,
                                   constant: constant)
} else if left.view.isDescendant(of: right.view) { // A is in B (LOW level)
    return right.view.addConstraint(item: left.view,
                                    attribute: left.attribute,
                                    toItem: right.view,
                                    attribute: right.attribute,
                                    multiplier: multiplier,
                                    constant: constant)
} else if right.view.isDescendant(of: left.view) { // B is in A (LOW level)
    return left.view.addConstraint(item: left.view,
                                   attribute: left.attribute,
                                   toItem: right.view,
                                   attribute: right.attribute,
                                   multiplier: multiplier,
                                   constant: constant)
}
```

Thinking about this issue made me think about something else important.
The way it was before, the `==` operator wasn't reflexive.
I mean that
```swift
view.Width == contentView.Width
contentView.Width == view.Width
```
was not generating the same constraint behind the hood. Mathematically speaking this was quite misleading.

thanks to fix we can write interchageably : 
```swift
avatar.Top == photo.Top + 10
photo.Top + 10 == avatar.Top
```

Here is the framework with the patch if you want to try it : 
[Stevia.framework.zip](https://github.com/freshOS/Stevia/files/1603601/Stevia.framework.zip)

Let me know what you think, 

and also...

Have a fantastic new year 2018 🍾 🎉 !

**Comment by s4cha** [comment]
@pbrazdil

The latest release is now live and should solve your problem :)
https://github.com/freshOS/Stevia/releases/tag/4.2.0

Let me know if everything works as expected ;)

**Comment by pbrazdil** [comment]
Thanks, I will let you know in case I will find any issues.
